# Services for Alarm Clock integration
snooze:
  name: Snooze Alarm
  description: Snooze the currently ringing alarm
  fields:
    device_id:
      name: Device ID
      description: The device ID of the alarm clock
      required: false
      selector:
        text:
    entity_id:
      name: Entity ID
      description: The entity ID of the alarm clock (for backward compatibility)
      required: false
      selector:
        entity:
          domain: sensor

dismiss:
  name: Dismiss Alarm
  description: Dismiss the currently ringing alarm
  fields:
    device_id:
      name: Device ID
      description: The device ID of the alarm clock
      required: false
      selector:
        text:
    entity_id:
      name: Entity ID
      description: The entity ID of the alarm clock (for backward compatibility)
      required: false
      selector:
        entity:
          domain: sensor

set_alarm:
  name: Set Alarm Time
  description: Set the alarm time
  fields:
    device_id:
      name: Device ID
      description: The device ID of the alarm clock
      required: false
      selector:
        text:
    entity_id:
      name: Entity ID
      description: The entity ID of the alarm clock (for backward compatibility)
      required: false
      selector:
        entity:
          domain: sensor
    time:
      name: Time
      description: The time to set the alarm (HH:MM format)
      required: true
      selector:
        time:

toggle_day:
  name: Toggle Day
  description: Toggle a day of the week for the alarm
  fields:
    device_id:
      name: Device ID
      description: The device ID of the alarm clock
      required: false
      selector:
        text:
    entity_id:
      name: Entity ID
      description: The entity ID of the alarm clock (for backward compatibility)
      required: false
      selector:
        entity:
          domain: sensor
    day:
      name: Day
      description: The day of the week to toggle
      required: true
      selector:
        select:
          options:
            - monday
            - tuesday
            - wednesday
            - thursday
            - friday
            - saturday
            - sunday

test_sound:
  name: Test Alarm Sound
  description: Test the alarm sound configuration by playing it once
  fields:
    device_id:
      name: Device ID
      description: The device ID of the alarm clock
      required: false
      selector:
        text:
    entity_id:
      name: Entity ID
      description: The entity ID of the alarm clock (for backward compatibility)
      required: false
      selector:
        entity:
          domain: sensor
